//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace HuaweiSoftware.Folder.FolderWCFReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FolderWCFReference.IFolderWCF")]
    public interface IFolderWCF {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IFolderWCF/AddListToDB", ReplyAction="http://tempuri.org/IFolderWCF/AddListToDBResponse")]
        System.IAsyncResult BeginAddListToDB(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<string>> folders, System.AsyncCallback callback, object asyncState);
        
        int EndAddListToDB(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IFolderWCF/Exists", ReplyAction="http://tempuri.org/IFolderWCF/ExistsResponse")]
        System.IAsyncResult BeginExists(string path, string name, System.AsyncCallback callback, object asyncState);
        
        bool EndExists(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IFolderWCF/GetId", ReplyAction="http://tempuri.org/IFolderWCF/GetIdResponse")]
        System.IAsyncResult BeginGetId(System.AsyncCallback callback, object asyncState);
        
        int EndGetId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IFolderWCF/GetFileFromDB", ReplyAction="http://tempuri.org/IFolderWCF/GetFileFromDBResponse")]
        System.IAsyncResult BeginGetFileFromDB(System.Nullable<int> PID, System.AsyncCallback callback, object asyncState);
        
        string EndGetFileFromDB(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IFolderWCF/GetDirFromDB", ReplyAction="http://tempuri.org/IFolderWCF/GetDirFromDBResponse")]
        System.IAsyncResult BeginGetDirFromDB(string path, System.AsyncCallback callback, object asyncState);
        
        string EndGetDirFromDB(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFolderWCFChannel : HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddListToDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddListToDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFileFromDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFileFromDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDirFromDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDirFromDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FolderWCFClient : System.ServiceModel.ClientBase<HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF>, HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF {
        
        private BeginOperationDelegate onBeginAddListToDBDelegate;
        
        private EndOperationDelegate onEndAddListToDBDelegate;
        
        private System.Threading.SendOrPostCallback onAddListToDBCompletedDelegate;
        
        private BeginOperationDelegate onBeginExistsDelegate;
        
        private EndOperationDelegate onEndExistsDelegate;
        
        private System.Threading.SendOrPostCallback onExistsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetIdDelegate;
        
        private EndOperationDelegate onEndGetIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFileFromDBDelegate;
        
        private EndOperationDelegate onEndGetFileFromDBDelegate;
        
        private System.Threading.SendOrPostCallback onGetFileFromDBCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDirFromDBDelegate;
        
        private EndOperationDelegate onEndGetDirFromDBDelegate;
        
        private System.Threading.SendOrPostCallback onGetDirFromDBCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public FolderWCFClient() {
        }
        
        public FolderWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FolderWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FolderWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FolderWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<AddListToDBCompletedEventArgs> AddListToDBCompleted;
        
        public event System.EventHandler<ExistsCompletedEventArgs> ExistsCompleted;
        
        public event System.EventHandler<GetIdCompletedEventArgs> GetIdCompleted;
        
        public event System.EventHandler<GetFileFromDBCompletedEventArgs> GetFileFromDBCompleted;
        
        public event System.EventHandler<GetDirFromDBCompletedEventArgs> GetDirFromDBCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF.BeginAddListToDB(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<string>> folders, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddListToDB(folders, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF.EndAddListToDB(System.IAsyncResult result) {
            return base.Channel.EndAddListToDB(result);
        }
        
        private System.IAsyncResult OnBeginAddListToDB(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<string>> folders = ((System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<string>>)(inValues[0]));
            return ((HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF)(this)).BeginAddListToDB(folders, callback, asyncState);
        }
        
        private object[] OnEndAddListToDB(System.IAsyncResult result) {
            int retVal = ((HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF)(this)).EndAddListToDB(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddListToDBCompleted(object state) {
            if ((this.AddListToDBCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddListToDBCompleted(this, new AddListToDBCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddListToDBAsync(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<string>> folders) {
            this.AddListToDBAsync(folders, null);
        }
        
        public void AddListToDBAsync(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<string>> folders, object userState) {
            if ((this.onBeginAddListToDBDelegate == null)) {
                this.onBeginAddListToDBDelegate = new BeginOperationDelegate(this.OnBeginAddListToDB);
            }
            if ((this.onEndAddListToDBDelegate == null)) {
                this.onEndAddListToDBDelegate = new EndOperationDelegate(this.OnEndAddListToDB);
            }
            if ((this.onAddListToDBCompletedDelegate == null)) {
                this.onAddListToDBCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddListToDBCompleted);
            }
            base.InvokeAsync(this.onBeginAddListToDBDelegate, new object[] {
                        folders}, this.onEndAddListToDBDelegate, this.onAddListToDBCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF.BeginExists(string path, string name, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExists(path, name, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF.EndExists(System.IAsyncResult result) {
            return base.Channel.EndExists(result);
        }
        
        private System.IAsyncResult OnBeginExists(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string path = ((string)(inValues[0]));
            string name = ((string)(inValues[1]));
            return ((HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF)(this)).BeginExists(path, name, callback, asyncState);
        }
        
        private object[] OnEndExists(System.IAsyncResult result) {
            bool retVal = ((HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF)(this)).EndExists(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExistsCompleted(object state) {
            if ((this.ExistsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExistsCompleted(this, new ExistsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExistsAsync(string path, string name) {
            this.ExistsAsync(path, name, null);
        }
        
        public void ExistsAsync(string path, string name, object userState) {
            if ((this.onBeginExistsDelegate == null)) {
                this.onBeginExistsDelegate = new BeginOperationDelegate(this.OnBeginExists);
            }
            if ((this.onEndExistsDelegate == null)) {
                this.onEndExistsDelegate = new EndOperationDelegate(this.OnEndExists);
            }
            if ((this.onExistsCompletedDelegate == null)) {
                this.onExistsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExistsCompleted);
            }
            base.InvokeAsync(this.onBeginExistsDelegate, new object[] {
                        path,
                        name}, this.onEndExistsDelegate, this.onExistsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF.BeginGetId(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetId(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF.EndGetId(System.IAsyncResult result) {
            return base.Channel.EndGetId(result);
        }
        
        private System.IAsyncResult OnBeginGetId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF)(this)).BeginGetId(callback, asyncState);
        }
        
        private object[] OnEndGetId(System.IAsyncResult result) {
            int retVal = ((HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF)(this)).EndGetId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetIdCompleted(object state) {
            if ((this.GetIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetIdCompleted(this, new GetIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetIdAsync() {
            this.GetIdAsync(null);
        }
        
        public void GetIdAsync(object userState) {
            if ((this.onBeginGetIdDelegate == null)) {
                this.onBeginGetIdDelegate = new BeginOperationDelegate(this.OnBeginGetId);
            }
            if ((this.onEndGetIdDelegate == null)) {
                this.onEndGetIdDelegate = new EndOperationDelegate(this.OnEndGetId);
            }
            if ((this.onGetIdCompletedDelegate == null)) {
                this.onGetIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetIdDelegate, null, this.onEndGetIdDelegate, this.onGetIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF.BeginGetFileFromDB(System.Nullable<int> PID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFileFromDB(PID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF.EndGetFileFromDB(System.IAsyncResult result) {
            return base.Channel.EndGetFileFromDB(result);
        }
        
        private System.IAsyncResult OnBeginGetFileFromDB(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Nullable<int> PID = ((System.Nullable<int>)(inValues[0]));
            return ((HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF)(this)).BeginGetFileFromDB(PID, callback, asyncState);
        }
        
        private object[] OnEndGetFileFromDB(System.IAsyncResult result) {
            string retVal = ((HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF)(this)).EndGetFileFromDB(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFileFromDBCompleted(object state) {
            if ((this.GetFileFromDBCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFileFromDBCompleted(this, new GetFileFromDBCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFileFromDBAsync(System.Nullable<int> PID) {
            this.GetFileFromDBAsync(PID, null);
        }
        
        public void GetFileFromDBAsync(System.Nullable<int> PID, object userState) {
            if ((this.onBeginGetFileFromDBDelegate == null)) {
                this.onBeginGetFileFromDBDelegate = new BeginOperationDelegate(this.OnBeginGetFileFromDB);
            }
            if ((this.onEndGetFileFromDBDelegate == null)) {
                this.onEndGetFileFromDBDelegate = new EndOperationDelegate(this.OnEndGetFileFromDB);
            }
            if ((this.onGetFileFromDBCompletedDelegate == null)) {
                this.onGetFileFromDBCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFileFromDBCompleted);
            }
            base.InvokeAsync(this.onBeginGetFileFromDBDelegate, new object[] {
                        PID}, this.onEndGetFileFromDBDelegate, this.onGetFileFromDBCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF.BeginGetDirFromDB(string path, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDirFromDB(path, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF.EndGetDirFromDB(System.IAsyncResult result) {
            return base.Channel.EndGetDirFromDB(result);
        }
        
        private System.IAsyncResult OnBeginGetDirFromDB(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string path = ((string)(inValues[0]));
            return ((HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF)(this)).BeginGetDirFromDB(path, callback, asyncState);
        }
        
        private object[] OnEndGetDirFromDB(System.IAsyncResult result) {
            string retVal = ((HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF)(this)).EndGetDirFromDB(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDirFromDBCompleted(object state) {
            if ((this.GetDirFromDBCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDirFromDBCompleted(this, new GetDirFromDBCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDirFromDBAsync(string path) {
            this.GetDirFromDBAsync(path, null);
        }
        
        public void GetDirFromDBAsync(string path, object userState) {
            if ((this.onBeginGetDirFromDBDelegate == null)) {
                this.onBeginGetDirFromDBDelegate = new BeginOperationDelegate(this.OnBeginGetDirFromDB);
            }
            if ((this.onEndGetDirFromDBDelegate == null)) {
                this.onEndGetDirFromDBDelegate = new EndOperationDelegate(this.OnEndGetDirFromDB);
            }
            if ((this.onGetDirFromDBCompletedDelegate == null)) {
                this.onGetDirFromDBCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDirFromDBCompleted);
            }
            base.InvokeAsync(this.onBeginGetDirFromDBDelegate, new object[] {
                        path}, this.onEndGetDirFromDBDelegate, this.onGetDirFromDBCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF CreateChannel() {
            return new FolderWCFClientChannel(this);
        }
        
        private class FolderWCFClientChannel : ChannelBase<HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF>, HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF {
            
            public FolderWCFClientChannel(System.ServiceModel.ClientBase<HuaweiSoftware.Folder.FolderWCFReference.IFolderWCF> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAddListToDB(System.Collections.ObjectModel.ObservableCollection<System.Collections.ObjectModel.ObservableCollection<string>> folders, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = folders;
                System.IAsyncResult _result = base.BeginInvoke("AddListToDB", _args, callback, asyncState);
                return _result;
            }
            
            public int EndAddListToDB(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("AddListToDB", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginExists(string path, string name, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = path;
                _args[1] = name;
                System.IAsyncResult _result = base.BeginInvoke("Exists", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndExists(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("Exists", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetId(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetId", _args, callback, asyncState);
                return _result;
            }
            
            public int EndGetId(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("GetId", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetFileFromDB(System.Nullable<int> PID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = PID;
                System.IAsyncResult _result = base.BeginInvoke("GetFileFromDB", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetFileFromDB(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetFileFromDB", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDirFromDB(string path, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = path;
                System.IAsyncResult _result = base.BeginInvoke("GetDirFromDB", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetDirFromDB(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetDirFromDB", _args, result)));
                return _result;
            }
        }
    }
}
